services:
  - docker
language: go
sudo: required
go:
  - "1.14.x"
dist: xenial

#env:
#  - GOPROXY=https://gocenter.io

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.25.4/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.17.5/bin/linux/amd64/kubectl
  - chmod +x kubectl
  - sudo mv kubectl /usr/local/bin/

install:
  - bash scripts/gogetcookie.sh
  - go get github.com/kardianos/govendor

script:
  - make k3s-start build testacc

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_deploy:
  - make build-binaries

#deploy:
#  provider: releases
#  skip_cleanup: true
#  api_key:
#    secure: C3jcmgMrQYoQD5JQ+3q3p5I2rwBstKKjfRKhY2SWKHc+J7g+Q51NGVMNYt3UUqK4tTsELYkrjATmoINKQF4KQmHiAnYmB9kyvTyHO/3mpGVMsmz9WujOJDN1/w2aPIYLGTKwj8wpzdWk7+MMLOTnsiZnYlhEgCVEzUAvY8GJK37kPqeZPdBLJXHMYJcg4xUaHJF9tdXesivD4pUqTQbQo1soXDk+yWIUAgRo366prUniwqMqD4lanjwT29MYdnCWTTFxvCWLhcFw8NQEhOq+qql5SJKYVjIiUQGmQT91CQ/4OHdMXalXZjKhinRKVsgA5/jydrlQcGmdCNufbcUwGPVwhhPLZrgvCOYZ0SXyetlVPTU9dh6tolUJiLI1pQB7RGnqLrAEXkQGyVTLfuK5+R22P+CwTxIEoU2bdMQDdh/R31Mnb3xbIOOSF2vG9RsXyTMmo1fI2//x08O/qlp+rWuXe7a+nInlkbZLTIC4VATeg2sYBWo52LcqYufgUsZDhz0YLRbntIkPaTeCoLKGMfIeVlsvRyjDCtE70UiClAb4RwemWw8nh64GnPCfCcCBecuC2670wp1bHHyskbI77KlTlQOZUVQ4e/QjLOroEDGXaKULWD6stel5iG1YL/M5mA+J6YbWw8s/9c6fyL6D1fqfbCamRYtvwzHYc4YtJsg=
#  file_glob: true
#  file: bin/*
#  on:
#    repo: gavinbunney/terraform-provider-kubectl
#    tags: true
